config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    resources :users do
      resource :profile
    end 
    
 root to: 'pages#home'
 get 'about', to: 'pages#about'
 resources :contacts, only: :create
 get 'contact-us', to: 'contacts#new'
 resources :friendships
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/filterables.rb
module Filterable
  extend ActiveSupport::Concern

  module ClassMethods
    def filter(filtering_params)
      results = self.where(nil)
      filtering_params.each do |key, value|
        results = results.public_send("filter_by_#{key}", value) if value.present?
      end
      results
    end
  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
    validates :name, presence: true
    validates :email, presence: true
    validates :comments, presence: true

#contact form validations

end 

app/models/friendship.rb
class Friendship < ActiveRecord::Base
    
    belongs_to :user
    belongs_to :friend, :class_name => "User"
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  has_many :users
end 

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  has_attached_file :avatar,
                    :style => { :medium => "300x300>", :thumb => "100x100>"},
                    :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :profile
  
  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    # GET request to /contact us
    #show new contact form
    def new
        @contact = Contact.new
    end
    
    #POST request /contacts
    
    def create
        #Mass assignment of form fields into contact object
        @contact = Contact.new(contact_params)
        #Save the contact object to the database
        if @contact.save 
            #store form fields via parameters into variables
            name = params[:contact][:name]
            email = params[:contact][:email]
            body = params[:contact][:comments]
            #plug variables into contact mailer email method and send eail
            ContactMailer.contact_email(name, email, body).deliver
            #store success in flash has and redirect to new actions
            flash[:success] = "Thank you for contacting us. 
            We will reply as soon as we can."
            redirect_to root_path
        else 
            #if contact object doesnt save store error in flash hash 
            #and redirect
            flash[:danger] = @contact.errors.full_messages.join(", ")
            redirect_to contact_us_path
        end 
    end 

    private
    #to collect data from form we need to use
    #strong parameters and whitelist the form fields
        def contact_params
            params.require(:contact).permit(:name, :email, :comments)
        end 
end

app/controllers/coupon_controller.rb
class CouponController
    
    def index
          if params[:store]
            @coupon = Coupon.where('store LIKE ?', "%#{params[:store]}%")
          else
            @coupon = Coupon.all
          end
    end




private 
    def coupon_params
  params.require(:coupon).permit(:store, :coupon_code)
    end
    

  
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def create
    @friendship = current_user.friendships.build(:friend_id => params[:friend_id])
    if @friendship.save
      flash[:notice] = "Added friend."
      redirect_to root_url
    else
      flash[:error] = "Unable to add friend."
      redirect_to root_url
    end
  end

  

  def destroy
    @friendship = current_user.friendships.find(params[:id])
    @friendship.destroy
    flash[:notice] = "Removed friendship."
    redirect_to current_user
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
 before_action :authenticate_user! 
  before_action :only_current_user

  # GET to /users/:user_id/profile/new
  def new
    @profile = Profile.new
  end
  
  # POST to /users/:user_id/profile
def create
  # Ensure that we have the user who is filling out form
  @user = User.find( params[:user_id] )
  # Create profile linked to this specific user
  @profile = @user.build_profile( profile_params )
  if @profile.save
    flash[:success] = "Profile updated!"
    redirect_to user_path( params[:user_id] )
  else
    render action: :new
  end
end

#GET request made to users/:user_id/profile/edit
def edit
  @user = User.find( params[:user_id]) 
  @profile = @user.profile
end

#PUSH and PUT for user/:user_id/profile
def update
  @user = User.find( params[:user_id]) 
  @profile = @user.profile
  if  @profile.update_attributes(profile_params)
    flash[:success]= "Profile Successfully Updated!"
    redirect_to user_path(id: params[:user_id])
  else
    render action :edit
  end
end

private


  def profile_params
    params.require(:profile).permit(:first_name, :last_name, :avatar, :city, :state, :zip, :contact_email, :description)
  end
  
  def only_current_user
    @user = User.find( params[:user_id] )
    redirect_to(root_url) unless @user == current_user
  end  
  
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  
  def index
    @users = User.includes(:profile) 
  end
 
 
 
  # GET to /users/:id
  def show
    @user = User.find( params[:id] )
  end
  
  
  
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendship_helper.rb
module FriendshipHelper
end

app/views/contacts/new.html.erb
<div class="container">
  <div class ="main">
    <div class="row">
        <h3 class="text-center">Contact Us</h3>
        <div class="col-md-4 col-md-offset-4">
          <% flash.each do |type, msg| %>
           <%= content_tag :div, msg, class: "alert-#{type}" %>
            <% end %>
          <div class="well">
            <%= form_for @contact do |f| %>
              <div class="form-group">
                <%= f.label :name %>
                <%= f.text_field :name, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :email %>
                <%= f.text_field :email, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :comments %>
                <%= f.text_area :comments, class: 'form-control' %>
              </div>
              <%= f.submit 'Submit', class: 'btn btn-default' %>
            <% end %>
          </div>
          </div>  
      </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Board Game Database</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Trade+Winds&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,600,700,800i&display=swap" rel="stylesheet"> 
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  
    <body>
      <div class="container">
        <div id=mySidenav class = "sidenav">
            <b href="javascript:void(0)" class="closebtn" onclick="closeNav()">Hide Menu &times;</b>
            <br>
            <br>
            <div id="Menu_login">
              <img class ="logo" src="https://mbgdb.s3.us-east-2.amazonaws.com/LogoMakr_95QFB2.png" alt="MYBGDB Logo">
                 <% if user_signed_in? %> 
                  <%= link_to('Logout', destroy_user_session_path, method: :delete, class:"btn btn-primary") %>        
                     <% else %>
                  <%= form_for(:user, :url => session_path(:user)) do |f| %>
                      <%= f.text_field :email, autofocus: true, placeholder: 'Enter Email' %>
                      <%= f.password_field :password, placeholder: 'Enter Password' %><br>
                      <%= f.check_box :remember_me %>
                      <%= f.label :remember_me %><br>
                      <%= f.submit 'Sign in' %><br><br>
                      <%= link_to "Forgot your password?", new_password_path(:user), class:"btn btn-primary" %>
                      <%= link_to "Sign up", new_registration_path(:user), class:"btn btn-primary" %>
                    <% end %>
                  <% end %>
                  <br>
              </div>    
              <ul class= "user_links"> 
                  <% if user_signed_in? %>
                    <% if current_user.profile %>
                      <li> <%= link_to "View My Collection", user_path(id: current_user.id) %></li>
                       <li> <%= link_to "Edit My Profile",  edit_user_profile_path(user_id: current_user.id) %> </li>
                       <li> <%= link_to "Find Other Members", users_path %></li>
                      <li> <%= link_to "Manage My Account", edit_user_registration_path %></li>
                       
                     <% else %>
                      <li><%= link_to "Create your profile to begin", new_user_profile_path(user_id: current_user.id) %></li>
                     <% end %> 
                     <% end %>
                  
                  </ul>
              <br>
              <ul>
                  <li><a href=page4.asp>Discover New Games</a></li>
                  <li><%= link_to "Home", root_path %></li>
                  <li><%= link_to "Contact Us", contact_us_path %></li>
                  <li><%= link_to "About Us", about_path %></li>
              </ul>    
                  
                 
              

                
              
          </div>
        </div>  
                <div class= "container_fluid"> 
                  <div class = main_head>
                   <div class="well header"
                      <header id="menu_label" >
                        <div class= "row">
                          <div class="col-md-4">
                                     <br><br><br>
                          <span style="font-size:30px;cursor:pointer" onclick="openNav();">&#9776; Menu & Login</span> 
                          </div>
                          <div class="col-md-2 col-md-offset-6">
                            <img id ="logo_top" src="https://mbgdb.s3.us-east-2.amazonaws.com/LogoMakr_95QFB2.png" alt="MYBGDB Logo">
                          </div>
                        </div>
                      </header>
                    </div>  
                  </div>
                </div>
             
                <div class="container flash-container">    
                  <% flash.each do |type, msg| %>
                  <%= content_tag :div, msg, class: "alert-#{type} text-center" %>
                  <% end %>
                </div>
         
          <%= yield %>
      </div>
    </div>
              <script>
                function openNav() {
                  
                  document.getElementById("mySidenav").style.width = "300px";
                  document.getElementById("menu_label").style.display = "none";
                  document.getElementById("mySidenav").style.overflowX="auto";
                  document.getElementsByClassName("main")[0].style.marginLeft = '325px';
                  document.getElementsByClassName("main_head")[0].style.marginLeft = '325px';
                }
                
                function closeNav() {
                  document.getElementsByClassName("main_head")[0].style.marginLeft = "25px";
                  document.getElementsByClassName("main")[0].style.marginLeft = "25px";
                  document.getElementById("mySidenav").style.width = "0";
                  document.getElementById("menu_label").style.display = "block";
                }
                </script> 
        </body>
  </div>
</html>

app/views/pages/about.html.erb
<body> 
  <div class="container-fluid">
    <div class ="main">
      
        <h2 class="text-center">About</h2><br><br><br><br><br><br><br>
             
        
        <br><p>Welcome to our new site. We wanted to create a place where the competition
        of boardgames could live. You are all keeping score, We want to make it better!
        </p>
        
    </div>
   </div> 
</body> 

app/views/pages/home.html.erb
 <body>   
    
        <div class = "main"> 
         <div class="container-fluid">  
             <div>
                 <h2>Build, Track, and Share Your Collection</h2>
                 <p>Welcome to your one stop shop to track the games you have, 
                 the games you want, and the games you never knew existed. 
                 It's free to join our community. Take a look around and let us
                 know what you think!</p>
              </div>
              <br><br><br>
                <div>
                  <div class=".col-xs-18 .col-sm-12"> 
                    </div>
                    <h2>Spotlight Games</h2> 
                        <div class= "row" class="text-center">
                           <div class=".col-xs-6 .col-sm-4 .col-xs-offset-6">   
                              <div class = "spotbox"> 
                                 <br>
                                 <img class ="game" src="https://mbgdb.s3.us-east-2.amazonaws.com/blur-board-game-business-challenge-278918.jpg" alt="This will be deleted">
                                 <h3>Settlers of Catan</h3> 
                                  <p>This is test. Test test testingly test. Short, sweet, to the point.
                                  Will eventually have a link.</p>
                              </div>  
                            </div>
                           <div class=".col-xs-6 .col-sm-4">    
                              <div class = "spotbox"> 
                                 <br>
                                 <img class ="game" src="https://mbgdb.s3.us-east-2.amazonaws.com/blur-board-game-business-challenge-278918.jpg" alt="This will be deleted">
                                 <h3>Exploding Kittens</h3> 
                                  <p>This is test. Test test testingly test. Short, sweet, to the point.
                                  Will eventually have a link.</p>
                              </div> 
                            </div>
                            
                            <div class=".col-xs-6 .col-sm-4">    
                              <div class = "spotbox"> 
                                 <br>
                                 <img class ="game" src="https://mbgdb.s3.us-east-2.amazonaws.com/blur-board-game-business-challenge-278918.jpg" alt="This will be deleted">
                                 <h3>Exploding Kittens</h3> 
                                  <p>This is test. Test test testingly test. Short, sweet, to the point.
                                  Will eventually have a link.</p>
                              </div> 
                            </div>
                            
                          <div class=".col-xs-6 .col-sm-4">    
                            <div class = "spotbox"> 
                               <img class ="game" src="https://mbgdb.s3.us-east-2.amazonaws.com/blur-board-game-business-challenge-278918.jpg" alt="This will be deleted">
                                <h3>Sparkle Kitty</h3> 
                                <p>This is test. Test test testingly test. Short, sweet, to the point.
                                Will eventually have a link.</p> 
                            </div> 
                          </div>
                        </div>
                      </div>
                    
            </div>   
        </div>
  </body>

app/views/profiles/_form.html.erb
<%= form_for @profile, url: user_profile_path,  :html => {:multipart => true} do |f| %>
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :city %>
    <%= f.text_field :city, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :state %>
    <%= f.text_field :state, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :zip %>
    <%= f.text_field :zip, class: 'form-control' %>
 </div>    
 <div class="form-group">
    <%= f.label :contact_email %>
    <%= f.text_field :contact_email, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
   <div>
    <%= f.label :avatar%>
    <%= f.file_field :avatar %><br>
  </div>
  <div class="form-group">
    <%= f.submit "Update Profile", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div class = "container">
  <div class = "main">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Edit Your Profile</h1>
        <p class="text-center">Update Your profile!</p>
        <div class="well">
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="main">
<div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Create Your Profile</h1>
        <p class="text-center">Be a part of the Game and fill out your profile!</p>
        <div class="well">
          <%= render 'form' %>
        </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class ="container-fluid">
  <div class="main">
      <div class="col-md-8 col-md-offset-2">
        <ul class="list-unstyled">
            <% @users.each do |user| %>
              <% if user.profile %>
                <li>
                  <div class="well row <%= cycle('silver-bg','')%>">
                    <div class = "col-sm-4 text_center">
                      <% if user.profile.avatar %>
                        <%= link_to user do %>
                          <%= image_tag user.profile.avatar.url, class: 'user-index-avatar' %>
                        <%end%>
                      <% end %>
                    </div>
                    <div class="index_text">
                      <%= link_to user do %>
                      <h2 class="index_name_link"><%= user.profile.first_name %> <%= user.profile.last_name %></h2>
                      <%end%>
                      <p class="text-center"><%= user.profile.city%> <%=user.profile.state%>, <%=user.profile.zip%></p>
                      
                      <%= link_to "Add Friend", friendships_path(:friend_id => user), :method => :post %>
                                  
                    </div>
                  </div>
                </li>
              <% end %>
            <% end %>
          </ul>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container-fluid">
  <div class ="main">
    <div class ="well well_show">  
      <div class = "row">
        <div class=col-md-2>
            <%= image_tag @user.profile.avatar.url, class: 'avatar_show_img'%>
        </div>
          <div class=col-md-8>
          
               <h1 class = "text-center"> <%= @user.profile.first_name %> <%= @user.profile.last_name %> </h1><br>
                <p class = "profile.text text-center"><b>Location:</b>  <%= @user.profile.city %>, <%= @user.profile.state %>  <%= @user.profile.zip %></p><br>
                 <p class = "profile.text text-center"><b>Email:</b> <%= @user.profile.contact_email %></p>
          </div>
        </div>
    </div>
     
          <div class="profile_show_text">
            <div class="well">
               <b>About Me: </b> <%= @user.profile.description %>
                 <h2>Friends</h2>
                    <ul>
                      <% for friendship in @user.friendships %>
                        <li>
                          <%=h friendship.friend.friend_ids %>
                          (<%= link_to "remove", friendship, :method => :delete %>)
                        </li>
                      <% end %>
                    </ul>
                    
                    <p><%= link_to "Find Friends", users_path %></p>
                    
                    <h2>Friended by Users</h2>
                    <ul>
                      <% for user in @user.inverse_friends %>
                        <li><%=h user.username %></li>
                      <% end %>
                    </ul>
               
            </div>
          </div>
          
                  
  </div>
</div>